### ISSUE TITLE
Dodanie 'double dummy' w PBN Viewerze

### ISSUE THREAD

**Issue by marekjarosz** [bbankowski/bridge_cc#13]
Obsłużenie tagów [OptimumResultTable] i [Minimax]. Być może udałoby się dodać do rozkładu (podobnie jak na sceenshocie) albo w innym sprytnym miejscu.
Tabelka OptimumResults nie zawsze musi mieć NESW w identycznej kolejności

![image](https://github.com/bbankowski/bridge_cc/assets/14911477/02a43a68-66b8-4fa8-ad87-58c1036d29ce)

Przykład:
```
[OptimumResultTable "Declarer;Denomination\2R;Result\2R"]
N C 10
N D 9
N H 8
N S 10
N NT 9
E C 3
E D 3
E H 5
E S 3
E NT 3
S C 10
S D 10
S H 8
S S 10
S NT 10
W C 3
W D 3
W H 5
W S 3
W NT 3
[Minimax "3NS630"]
```

> 5.7	 OptimumResultTable
> ----------------------
>   This table shows the optimum result of a deal in number of tricks, with
> open cards (double dummy). For each direction, being the declarer, and for
> each denomination the maximum number of tricks is given based on optimum
> declarer play and optimum defence. A full table consists of 20 rows. The
> table has 3 predefined columns with names:
>     Declarer        direction of declarer: W, N, E, S 
>     Denomination    S, H, D, C, NT 
>     Result          number of tricks won by declarer: 0 .. 13

**Comment by bbankowski** [comment]
Dodane.
