### ISSUE TITLE
Znaczniki kolorów nie są dekodowane w komentarzach do licytacji

### ISSUE THREAD

**Issue by marekjarosz** [bbankowski/bridge_cc#14]
Znaczniki kolorów nie są dekodowane w komentarzach do licytacji
Przykład w treningu z 2024.01.11, rozdanie 10

![image](https://github.com/bbankowski/bridge_cc/assets/14911477/cb1ca791-9f67-4a45-aba7-d443e6dce97a)

**Comment by bbankowski** [comment]
Poprawione.
