### ISSUE TITLE
Odpowiednie utrzymanie pliku z systemem

### ISSUE THREAD

**Issue by marekjarosz** [bbankowski/bridge_cc#3]
Sekcje w pliku, tak żeby połapać się przy edycji

**Comment by bbankowski** [comment]
Możemy ew. podzielić na kilka plików, pytanie co będzie wygodniejsze.

**Comment by marekjarosz** [comment]
jak sto lat temu tworzyłem ten dokument w html (co się śmiałeś, że uzupełniany ręcznie), to wtedy był podział na:
- otwarcia
- interwencje po każdym otwarciu
- licytacja w obronie

Wydaje mi się, że tego typu podział byłby sensowny :)

**Comment by bbankowski** [comment]
Przy okazji trochę pozmieniałem format, teraz plik jest .txt, w środku opis co i jak.

**Comment by marekjarosz** [comment]
podzieliłem wnętrze pliku, żeby łatwiej się na to patrzyło
