### ISSUE TITLE
Większe wcięcia jeżeli sekwencja dłuższa niż 4 odzywki

### ISSUE THREAD

**Issue by marekjarosz** [bbankowski/bridge_cc#4]
Nie dalej niż sekwencja cztero-odzywkowa, czyli jak mamy 1C-2K-2C-2BA: możemy dalej napisać 3C-3P-3BA, ale wizualnie to już będzie się zwijać poprzez kolejne wcięcie (czyli w stylu strony dodać third, fourth level), np:
![dluga_sekwencja](https://cloud.githubusercontent.com/assets/14911477/10201563/fc5c554c-67ac-11e5-96dd-2bc6e0a21063.png)

**Comment by bbankowski** [comment]
Łatwo nie było, ale coś tam się udało. Prezentacja nie jest jak u Ciebie w przykładzie, ale są rozdzielone dalsze okrążenia licytacji i w nich są kolejne wcięcia.

**Comment by marekjarosz** [comment]
wygląda na to że jest git :+1:
