### ISSUE TITLE
Licytacja po interwencji

### ISSUE THREAD

**Issue by marekjarosz** [bbankowski/bridge_cc#8]
Obsługa licytacji po interwencji, w jaki sposób to wpisywać a później wyświetlać.

**Comment by bbankowski** [comment]
Zrobione częściowo.

Licytacja po interwencji rozpoczyna się od *.
Licytacja w obronie rozpoczyna się od ^.

Póki co nie da się zrobić dwóch znaczeń dla jednej odzywki. Np. licytacja w obronie po słabym 1BA i klasycznym 1BA. Narazie proponuje wpisywać tak jak jest, a ja to jeszcze poprawię, żeby dało się to łatwo ogarnąć.

**Comment by bbankowski** [comment]
Zmieniłem format dla licytacji w obronie. Wpisujemy:

^ Obrona po 1BA klasycznym

i dalej już standardowo, aż do kolejnego ^.

Ważne: najpierw trzeba wpisać licytację jednostronną, później po interwencji, a na końcu dopiero w obronie.

**Comment by bbankowski** [comment]
To samo działa dla licytacji po interwencji:

\* opis
1T-2T-3T-...

^ opis
1T-2T-3T-...
